// This file will be generated by Amplify Gen 2
// For now, we'll use a placeholder that will be replaced during deployment
export const amplifyConfig = {
  // Will be populated by Amplify Gen 2 backend
};


